### PR TITLE
Fix: footer timekeeper logo blackening on doc routes

### LINKED ISSUE #68: Clock logo in footer of docs page is messed up
Screenshot-2023-07-13-at-12-03-36-AM</img>

### PR DESCRIPTION
**Pull request by Akalanka47000**
Fixes #68

### CODE REVIEW

**Comment by Akalanka47000** [comment]
@Dhruv-Sood this should fix it, can you confirm it once please? Once that's done we're good for merging

**Comment by Dhruv-Sood** [comment]
Working fine now!!

**Review by Dhruv-Sood — COMMENTED** [review]
Working Fine Now!!

**Review by Dhruv-Sood — APPROVED** [review]

**Comment by Akalanka47000** [comment]
> Working Fine Now!!

Nice, forgot to switch on auto merge before going off, let's merge it now

**Pull request merged**
