### PR TITLE
Fix: remove logo outline

### LINKED ISSUE #62: Remove border around logo on focus
image

image

image

### PR DESCRIPTION
**Pull request by sohaibaumer**
Fixes #62 

Verified in Chorme, Firefox and Edge.

### CODE REVIEW

**Review by Akalanka47000 — CHANGES_REQUESTED** [review]
Hi @sohaibaumer, the issue still seems to be present. Way to replicate:-

1. Select the svg node from inspect element
2. Right click and force state to focus

image

Perhaps we could try applying outline none on focus to all svgs globally, just noticed that the same issue is present in the other logos/ icons as well

**Comment by sohaibaumer** [comment]
I have targeted the logo svg through immediate parent using arbitrary values, however, let me re-check. 
PS, the requirement specifically mentioned logo, thats why I didn't target svgs globally but that can be done.

**Comment by Akalanka47000** [comment]
> I have targeted the logo svg through immediate parent using arbitrary values, however, let me re-check. PS, the requirement specifically mentioned logo, thats why I didn't target svgs globally but that can be done.

Got it, I'm not sure either why the arbitrary values didn't work, the styles hadn't been applied once the checked through inspect. Anyways let me know once this is good to merge. It seems to be working fine now.

**Comment by sohaibaumer** [comment]
Note: some of the styling particularly in the getting started page kept getting overwritten, so I re-pushed with !important. Its working now I believe, you can check.

**Comment by Akalanka47000** [comment]
> Note: some of the styling particularly in the getting started page kept getting overwritten, so I re-pushed with !important. Its working now I believe, you can check.

Looks good to me

**Review by Akalanka47000 — APPROVED** [review]

**Pull request merged**
