### PR TITLE
Highlight header github icon and footer socials on hover

### PR DESCRIPTION
**Pull request by nikohoffren**
Added hover effects to GitHub icon and footer socials with their representative colors using Tailwind CSS.

### CODE REVIEW

**Review by Akalanka47000 — CHANGES_REQUESTED** [review]
Hi, shall we change the color to maybe like text-black/80 ?  As you can see it's quite a minimal design without multiple colors. Also shall we add in a transition? Let's use the duration-medium  property which is defined in the config file.

Let's move the defined class set to a tailwind utility name something like icon-hover, it'll allow for resuse.

Also I happened to notice that the social icons visually look different in size, do you think you can fix it as well ?

**Comment by nikohoffren** [comment]
Sure, i'll do those changes.

**Comment by nikohoffren** [comment]
Hey, i added color black-opacity-80, used it with duration-medium transition and added as utility called icon-hover to index.css. Also added social icon width and height so they all should be in similar size.

**Review by Akalanka47000 — APPROVED** [review]
Looking good, merging this in. Thank you for the support:)

**Pull request merged**
