### PR TITLE
Dhruv branch

### PR DESCRIPTION
**Pull request by Dhruv-Sood**
This pull request address issue #63

### CODE REVIEW

**Review by Akalanka47000 — CHANGES_REQUESTED** [review]
Hi, thanks for the PR.

There are a few issues blocking me from merging this in however. The styles applied are affecting the logo of the hero section as well, and the rotation offset isn't at the center.

Further, we're only using vanilla CSS only for styling which cannot be done or difficult to do with Tailwind, this effect is already available out of the box as tailwind classes.

Will you be free to look at these issues ?

We also are using PNPM as the package manager and as such the package-lock.json should not be added to source control, I'll open an issue to add it to the .gitignore file. It'll stop this issue from surfacing again.

**Comment by Dhruv-Sood** [comment]
Sure I'll do as asked

**Comment by Dhruv-Sood** [comment]
In my new commit I used tailwind css keeping the rotate offset center

**Comment by Akalanka47000** [comment]
> In my new commit I used tailwind css keeping the rotate offset center

Looks good, shall we use an arbitary value for the rotation angle, we can use this class `rotate-[20deg]` since it's a one time usage without making changes to the config file. Also maybe rename the flag to `tilt` since it's not a full rotation ?

**Comment by Dhruv-Sood** [comment]
My apologies! I am not familiar with tailwind so I read some docs and changed the config file. But now I have used arbitrary value as mentioned and completed the fixes!
Thanks for guiding

**Comment by Akalanka47000** [comment]
> My apologies! I am not familiar with tailwind so I read some docs and changed the config file. But now I have used arbitrary value as mentioned and completed the fixes! Thanks for guiding

No worries:)

**Review by Akalanka47000 — APPROVED** [review]

**Pull request merged**
